"""Exceptions package."""

from issue_creator.exceptions.exceptions import IssueCreationError  # noqa: F401
